#!/usr/bin/bash

# Simple pre commit hook, always runs for all files
# for more complicated project you would probably like to use pre-commit tool: https://pre-commit.com

set -e

echo -e "-- Running clang-format"
clangformatout=$(git clang-format --style=Google --diff -q)  
  
if [ "$clangformatout" != "" ]  
then
    echo "Format error!"
    echo "Use git clang-format"
    exit 1
fi

added_files=$(git diff --cached --name-only)

if [ ! -z "$added_files" ]; then
    source_files=$(echo $added_files | grep -e ".*\.\(cpp\|cxx\|h\|hpp\)" | cat)
fi

if [ ! -z "$source_files" ]
then
    echo -e "\n-- Running cpplint\n"
    cpplint $source_files
fi

if [ ! -d "build" ] 
then
    echo -e "\n-- Running cmake buildn"
    mkdir build
    (cd build; cmake ..; make -j4)
fi

echo -e "\n-- Running ctest\n"
(cd build; ctest --output-on-failure -j4)
