#!/usr/bin/bash

# Simple pre commit hook, always runs for all files
# for more complicated project you would probably like to use pre-commit tool: https://pre-commit.com

set -e

echo -e "-- Running clang-format"
clangformatout=$(git clang-format --style=file --diff --staged -q)  
  
if [ "$clangformatout" != "" ]  
then
    echo "Format error!"
    echo "Use git clang-format"
    exit 1
fi

added_files=$(git diff --cached --name-only)

if [ ! -z "$added_files" ]; then
    source_files=$(echo $added_files | tr " " "\n" | grep -e ".*\.\(cpp\|cxx\|h\|hpp\)" | cat)
fi

if [ ! -d "build" ] 
then
    echo -e "\n-- Running cmake"
    mkdir build
    (cd build; cmake ..)
fi

if [ ! -z "$source_files" ]
then
    echo -e "\n-- Running clang-tidy\n"
    clang-tidy -p build/ -header-filter=. $source_files
fi

echo -e "\n-- Running make && ctest\n"
(cd build; make -j4; ctest --output-on-failure -j4)
